random module generates pseudo random sequence that can be re generatable

In [1]:
import random

In [33]:
n=random.random() #produces random float in range 0--1
print(n)


o=random.randint(1,15)#produces random int in given range
print(o)

d=random.uniform(1,15)#produces random float in given range 
print(d)

p=random.randrange(1,12)#produces random int in given range upper bound not included
print(p)

0.5938771477972168
11
11.442848523728431
2


In [36]:
a=random.normalvariate(0,5) )#produces random no. from standered distribution  with mu and sigma as imput
print(a)

-1.7365864036428862


In [37]:
ra=list("hello python")
print(ra)

['h', 'e', 'l', 'l', 'o', ' ', 'p', 'y', 't', 'h', 'o', 'n']


In [49]:
rachoice=random.choice(ra)#picks random element from list
print(rachoice)

rachoice1=random.sample(ra,2)#picks random element from list with desired length
print(rachoice1)

rachoice2=random.choices(ra,k=3)#picks random element from list with desired length and elements can be repeated twice in seletion
print(rachoice2)


p
['l', 'h']
['l', 'l', 'e']


In [50]:
print(ra)
random.shuffle(ra) #shuffle in place 
print(ra)

['h', 'e', 'l', 'l', 'o', ' ', 'p', 'y', 't', 'h', 'o', 'n']
['o', 'l', 'l', 'h', 'n', 'y', 'h', 'e', 't', 'p', ' ', 'o']


same seeds pproduces same random no. everytime

In [58]:
random.seed(1)
print(random.random())
print(random.randint(1,10))
random.seed(2)
print(random.random())
print(random.randint(1,10))
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.13436424411240122
14


real random no. are generated by secrets module

In [59]:
import secrets

In [61]:
a=secrets.randbelow(15)#generates random no. below input bound
print(a)

b=secrets.randbits(4)# generates random no with input bit length
print(b)

mlist=list("helloover") #picks random element from list
c=secrets.choice(mlist)
print(c)

7
4
o


random can be applied to numpy array

In [67]:
import numpy as np
np.random.seed(1)
print(np.random.rand(3))

# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0, 10, (5,3))
print(values)

# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)


[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]
[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
