In [1]:
import numpy  as np

In [29]:
a=np.zeros(10) #makes zero element arrray with given length 
print(a) #default data is float type
print(a[1])
a.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0


10

In [17]:
a.shape #gives shape(dimentions) of array

(10,)

In [18]:
a.shape=(10,1)

In [19]:
print(a[1])

[0.]


In [20]:
b=np.ones(10)#creates array with ones
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
c=np.empty(15)#creates array of given lengthwith un initialized values 
c

array([4.66161281e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [43]:
d=np.linspace(1,100,10)#creates array with  10 elements from 1 to 100
d

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])